function [Accuracy_Threshold, DetermineInt] = ProbabilityMethod(P_binCombos, threshold)

load('C:\Users\Britt\Dropbox (MIT)\Faridpur\Manuscripts\SoilKitPaper\Figures\DatasetForPaper.mat')

% want a table with:
% 1) avg XRF As for each set of 12 in AllSeasons
DetermineInt = grpstats(AllSeasons,{'Site','Type','Season'},{'mean','sem'},...
    'DataVars',{'As_XRF' 'As_Kit'});
% 2) column of intervene vs no for avg XRF As   above vs below threshold
DetermineInt.Intervene_XRF = DetermineInt.mean_As_XRF > threshold;

for n = 1:height(DetermineInt)
    kitVals = AllSeasons.As_Kit(AllSeasons.Site == DetermineInt.Site(n) &...
        AllSeasons.Type == DetermineInt.Type(n) & AllSeasons.Season == DetermineInt.Season(n));
    kitVals = sort(kitVals);
    DetermineInt.probAsGreaterThanCutoff(n) = P_binCombos.probAsGreaterThanCutoffGivenBins(...
        P_binCombos.Bin1 == kitVals(1) & P_binCombos.Bin2 == kitVals(2) &...
        P_binCombos.Bin3 == kitVals(3) & P_binCombos.Bin4 == kitVals(4) &...
        P_binCombos.Bin5 == kitVals(5) & P_binCombos.Bin6 == kitVals(6) &...
        P_binCombos.Bin7 == kitVals(7) & P_binCombos.Bin8 == kitVals(8) &...
        P_binCombos.Bin9 == kitVals(9) & P_binCombos.Bin10 == kitVals(10) &...
        P_binCombos.Bin11 == kitVals(11) & P_binCombos.Bin12 == kitVals(12));
end

for n = 0:100
    DetermineInt.Intervene_Kit_Prob = DetermineInt.probAsGreaterThanCutoff > n/100;
    AccurateMoreThanThreshold = height(DetermineInt(DetermineInt.Intervene_XRF & DetermineInt.Intervene_Kit_Prob,:));
    InaccurateMoreThanThreshold = height(DetermineInt(DetermineInt.Intervene_XRF & ~DetermineInt.Intervene_Kit_Prob,:));
    AccurateThresholdorLess = height(DetermineInt(~DetermineInt.Intervene_XRF & ~DetermineInt.Intervene_Kit_Prob,:));
    InaccurateThresholdorLess = height(DetermineInt(~DetermineInt.Intervene_XRF & DetermineInt.Intervene_Kit_Prob,:));
    Accuracy_Threshold(n+1,1:5) = [n AccurateThresholdorLess InaccurateThresholdorLess...
        AccurateMoreThanThreshold InaccurateMoreThanThreshold]; 
end

Accuracy_Threshold = array2table(Accuracy_Threshold,'VariableNames',...
    {'ProbabilityThreshold' 'AccurateThresholdorLess','InaccurateThresholdorLess','AccurateMoreThanThreshold','InaccurateMoreThanThreshold'});
Accuracy_Threshold.PctFalsePos = Accuracy_Threshold.InaccurateThresholdorLess./...
    (Accuracy_Threshold.AccurateThresholdorLess + Accuracy_Threshold.InaccurateThresholdorLess);
Accuracy_Threshold.PctFalseNeg = Accuracy_Threshold.InaccurateMoreThanThreshold./...
    (Accuracy_Threshold.AccurateMoreThanThreshold + Accuracy_Threshold.InaccurateMoreThanThreshold);
Accuracy_Threshold.PctFalseOverall = (Accuracy_Threshold.InaccurateMoreThanThreshold+...
    Accuracy_Threshold.InaccurateThresholdorLess)./(Accuracy_Threshold.AccurateMoreThanThreshold +...
    Accuracy_Threshold.InaccurateMoreThanThreshold + Accuracy_Threshold.AccurateThresholdorLess +...
    Accuracy_Threshold.InaccurateThresholdorLess);
Accuracy_Threshold.PosNegDiff = Accuracy_Threshold.PctFalsePos - Accuracy_Threshold.PctFalseNeg;
